### ISSUE TITLE
Change request: switch to the frontend-component-header

### ISSUE THREAD

**Issue by dyudyunov** [openedx/frontend-app-learner-dashboard#178]
### The problem

Instead of using the [frontend-component-header](https://github.com/openedx/frontend-component-header) the MFE uses its own [LearnerDashboardHeader](https://github.com/openedx/frontend-app-learner-dashboard/blob/master/src/containers/LearnerDashboardHeader/index.jsx) component. Main pain points here:

- it’s a third header on the platform (including the legacy header and the header component used by other MFEs) which is confusing for users
- it has hardcoded edx’s values, like the edx logo, which I believe will be a violation of the trademark policies if used elsewhere
![image](https://github.com/openedx/frontend-app-learner-dashboard/assets/47273130/a04540af-f3b4-42c5-8ce0-c1b11790e30a)

### Proposal
It would be great to replace it with the easily-brandable frontend-component-header.

### Additional info
- [openedx discussion post](https://discuss.openedx.org/t/learners-dashboard-mfe-is-not-ready-for-usage-in-community/10697/1)

**Comment by adamstankiewicz** [comment]
[inform] Just dropping some helpful links for whenever this issue gets picked up: 

* Hardcoded edX.org production logo: 
https://github.com/openedx/frontend-app-learner-dashboard/blob/c01042f1dfd683c3dfc8366093f8ced601b33888/src/containers/LearnerDashboardHeader/BrandLogo.jsx#L17
* Ideally, instead of hardcoding the logo URL as shown above, it'd rely on the configured `LOGO_URL`, e.g. `getConfig().LOGO_URL`: https://github.com/openedx/frontend-app-learner-dashboard/blob/c01042f1dfd683c3dfc8366093f8ced601b33888/.env.development#L8

**Comment by mariajgrimaldi** [comment]
This was partially solved by: https://github.com/openedx/frontend-app-learner-dashboard/pull/205, which makes it customizable by adding an environment variable. Which value is read during build time. So we would need to add support for the MFE Config for a more flexible solution as Adam mentioned. Although I'm wondering why are we using a custom header instead of the [LearningHeader](https://github.com/openedx/frontend-component-header/blob/f3637b56243d743914c8e59a886f60ce8fba7925/src/learning-header/LearningHeader.jsx#L28-L62) -- or a similar version?

**Comment by mariajgrimaldi** [comment]
Here's a PR with the suggested change: https://github.com/openedx/frontend-app-learner-dashboard/pull/238

**Comment by jsnwesson** [comment]
Hey all, just wanted to jump in to say that my team (@openedx/2u-aperture, soon-to-be-maintainers) and I fully support replacing the header with the default MFE Header. We'll definitely want to know when that change is ready to happen, but as a heads up we'd want to ensure two things in order to accept the PR: 
1. The "Careers" option still appears for edX.org users ([original PR with screenshots](https://github.com/openedx/frontend-app-learner-dashboard/pull/152), fair warning that there is a bug somewhere that is hiding this)
2. The learner will still be able to toggle between their dashboard or one of the available **Enterprise** dashboards via the modal or dropdown.

<img width="1800" alt="Screenshot 2023-11-08 at 1 42 42 PM" src="https://github.com/openedx/frontend-app-learner-dashboard/assets/62807795/f2105407-238a-4133-ae41-075027e66c9b">
<img width="362" alt="Screenshot 2023-11-08 at 1 42 48 PM" src="https://github.com/openedx/frontend-app-learner-dashboard/assets/62807795/3e32c897-a3bd-4cd2-8d63-7f5aebfc53e6">

**Comment by mariajgrimaldi** [comment]
@jsnwesson: thanks for the details! I don't know how much work it would be to change the header, but when we have it done, is it enough to have flags to turn on/off both dashboards? Unless we have a replacement for the community, I'll tag @arbrandes here. Should we talk with the product wg for this one?

**Comment by jsnwesson** [comment]
@mariajgrimaldi I would say it's enough to have flags for the dual dashboard feature! 
I'm not involved as much with the argument for certain Header implementations over others, but I would imagine that if we ever want to make it so the Header and Footer can be wrapped around all MFEs (Piral being one method that comes to mind), then we'd want to stick with the same Header/Footer dependencies across the board.

**Comment by hinakhadim** [comment]
Hi everyone, Just want to know if anyone is actively working on this at the moment? or Are we paused because of "Careers" option and dual dashboard thing. 
What if we'll include both things in `@edx/frontend-component-header` and use that header package in all MFEs for UI consistency or is there any problem in that? Looking forward to your thoughts on this so that I can create PR.

**Comment by jsnwesson** [comment]
Hi @hinakhadim ! As it turns out, I believe the @openedx/2u-vanguards team is planning on bringing in the customized header into `@edx/frontend-component-header`. @zainab-amir is that still accurate?

**Comment by 0x29a** [comment]
Hi @zainab-amir and @openedx/2u-vanguards, just wanted to know whether what @jsnwesson wrote above is correct and if anyone is working on this at the moment? One of our clients is interested in making the header look consistent across all MFEs, so depending on what needs to be done, we could probably create a PR as well or help with an existing one if needed. Looking forward to your thoughts.

**Comment by syedsajjadkazmii** [comment]
Hi @0x29a, yes its correct. We have launched configurable header feature in [v5.2.0](https://github.com/openedx/frontend-component-header/releases/tag/v5.2.0) and we currently working on replacing custom header with frontned-component-header in learner-dashboard.

cc: @ahtesham-quraish

**Comment by 0x29a** [comment]
That's awesome, @syedsajjadkazmii! Thank you and your team for working on this. Please let us know if we can help anyhow.

**Comment by arbrandes** [comment]
This is the relevant PR, if I'm not mistaken:

https://github.com/openedx/frontend-app-learner-dashboard/pull/327

**Comment by zainab-amir** [comment]
@arbrandes yes, that is the PR to replace the learner dashboard custom header with `frontend-component-header`. We have a small followup PR that needs your review: https://github.com/openedx/frontend-component-header/pull/494
