### ISSUE TITLE
Missing internationalization

### ISSUE THREAD

**Issue by arbrandes** [openedx/frontend-app-learner-dashboard#287]
As per https://discuss.openedx.org/t/translations-issues-with-the-frontend-app-learner-dashboard/12287, @sambapete writes:

> (...) not all string ids in the various messages.js files found in the repository are properly harvested, collected and sent to Transifex for translations.
>
> If you look at the course card on the dashboard, you will see for example that the string “Begin Course” and other strings remain in English for all languages. You can easily check that by switching languages in [edx.org](http://edx.org/) or in your own Open edX instances running Quince for example.
>
> That’s because the strings in src/containers/CourseCard/components/CourseCardActions/messages.js never made it to src/i18n/messages/fr_CA.json or any other files that would be used for translating various languages in the MFE. Check for the id learner-dash.courseCard.actions.beginCourse and you will not find it in the strings that the Translations Working Group needs to translate in Transifex.

**Comment by OmarIthawi** [comment]
Thanks @sambapete and @arbrandes for reporting this issue.

I've checked the file and it's a bug in the `messages.js`:

https://github.com/openedx/frontend-app-learner-dashboard/blob/32681652334271daf6ed54a9974836a5c70b3d35/src/containers/CourseCard/components/CourseCardActions/messages.js#L1-L12

It's using the `StrictDict` instead of the `defineMessage` as seen in other files:

https://github.com/openedx/frontend-app-learner-dashboard/blob/32681652334271daf6ed54a9974836a5c70b3d35/src/containers/LearnerDashboardHeader/messages.js#L1-L13

To fix the issue, the `CourseCard/components/CourseCardActions/messages.js` should be refactored to use `defineMessage` and it'll make it to transifex shortly (the following day or so).

**Comment by sambapete** [comment]
You might want to check in all messages.js files then because it is not limited to CourseCard.

StrictDict is being used in most messages.js files under frontend-app-learner-dashboard//src/containers/

Take for example src/containers/UnenrollConfirmModal/components/messages.js or ./src/containers/SelectSessionModal/messages.js

A full review may be needed...

**Comment by sambapete** [comment]
This will fix the problem with CourseCardActions but not all problems.

The same issue exists in other messages.js files in frontend-app-learner-dashboard.

A full review may be needed.

Look at src/containers/SelectSessionModal/messages.js, ./src/containers/CourseCard/components/CourseCardMenu/messages.js and a few others that are also using StrictDict.

And it may be the case in other dirctories.

**Comment by ghassanmas** [comment]
@sambapete I have made a quick serach across `openedx` org in github, and it seems this only used learner-dashbaord, 
Search link: https://github.com/search?q=org%3Aopenedx+%22export+const+messages+%3D+StrictDict%28%22&type=code 

For other MFEs I think the problem we had before that the resources werent synced to TX in the first place. 

Regarding a test I agree it would be ideal, so far to my knowledge there are two reason a resource is not TX:( 1. The repo is not synced and 2. The sytanx used to define a message ). 
  
We will discuss this topic in next TWG call CC:@ehuthmacher

**Comment by sambapete** [comment]
Thanks @ghassanmas 

At least we know it is restricted to this MFE. Since the problem also affects edx.org, maybe it could be given a higher priority to resolve?
